### PR TITLE
fixes date range list for ULM Calendar Weekly and Monthly intervals

### LINKED ISSUE #426: ULM Standard Date Range Options not shown for Calendar Week and Month intervals
The new Calendar Week and Month interval options weren't set up with a list of standard date range selections, so the standard range option list doesn't show in the date range picker when those intervals are selected.

### PR DESCRIPTION
**Pull request by sandikbarr**
closes #426

### CODE REVIEW

File: src/app/shared/menu/date/standard-date-range.component.ts [hunk 1]
```diff
@@ -34,34 +34,29 @@ export class StandardDateRangeComponent implements OnChanges {
...
-          dateUtil.LAST_7_DAYS,
-          dateUtil.THIS_MONTH,
-          dateUtil.LAST_MONTH,
-          dateUtil.LAST_28_DAYS,
-          dateUtil.LAST_30_DAYS,
-          dateUtil.THIS_YEAR,
-          dateUtil.LAST_YEAR,
-          dateUtil.LAST_365_DAYS
-        ];
+    if (this.interval === INTERVAL_HOURLY) {
```
Comment (sandikbarr) [inline src/app/shared/menu/date/standard-date-range.component.ts:37]: HOURLY has a shorter list of date ranges because it doesn't support that wide of a date range, but the rest are the same so that switch statement wasn't very appropriate.

**Review by cavis — APPROVED** [review]
👍
